### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by gbalabasquer**
- Removes GNT usage
- Uses `uint256` and `int256`

### CODE REVIEW

**Comment by gbalabasquer** [comment]
We might want to convert the contract to a `library`, this way we avoid the wrong usage as a central contract.
The only negative thing is we can't inherit `Common` anymore, so we should to triplicate those functions.

**Review by lucas-manuel — APPROVED** [review]
Tests pass, LGTM

**Comment by gbalabasquer** [comment]
I've modified the base branch to a fork from `master` called `dev`. This way we can add all the desired changed in this new branch before merging finally to `master`. Ideally we should only do that when we are prepared to change the official deployed proxy actions contract addresses.

**Comment by lucas-manuel** [comment]
> I've modified the base branch to a fork from `master` called `dev`. This way we can add all the desired changed in this new branch before merging finally to `master`. Ideally we should only do that when we are prepared to change the official deployed proxy actions contract addresses.

Good call.

**Review by kmbarry1 — APPROVED** [review]
LGTM

**Pull request merged**
